### ISSUE TITLE
No longer works with jQuery 3.6

### ISSUE THREAD

**Issue by sgruendel** [tlemens/jquery-ui-monthpicker#2]
Stopped working with jQuery 3.6, formatted dates only contain "undefined" / "NaN".

**Comment by tlemens** [comment]
Hi Stefan, are you still using jQuery? :) ... it has been 7 years since my last commit here ... if you want, you make a fix and I will merge it here ... otherwise I think I am going to archive this project

**Comment by sgruendel** [comment]
Hi Clemens, not my choice, my employer forces me :) Just pushed a PR which fixes it for me, should also be backwards compatible.
